"""robotid

Revision ID: 85c9428aa8ee
Revises: a8c2af7fc817
Create Date: 2023-04-20 17:17:38.303158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85c9428aa8ee"
down_revision = "a8c2af7fc817"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("robot_ID", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("robot_ID")

    # ### end Alembic commands ###
