"""robo

Revision ID: daffea9bd5b1
Revises: d441d7dc8b6f
Create Date: 2023-04-21 11:00:16.320358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daffea9bd5b1'
down_revision = 'd441d7dc8b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_link', sa.String(length=100), nullable=True))
        batch_op.drop_column('character')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('profile_link')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
